### ISSUE TITLE
No Typescript types defined (*.d.ts file)

### ISSUE THREAD

**Issue by chriscapaci** [gajus/express-tus#2]
I'm working on creating a workaround for this by adding "express-tus" to DefinitelyTyped, but it would be better if the type definitions came directly from the actual package. Can you add them? You can probably do it in a better way than this, but here ([index.d.ts.txt](https://github.com/gajus/express-tus/files/5974896/index.d.ts.txt)) is the file I'm trying to use with DefinitelyTyped.

**Comment by gajus** [comment]
Rewrite to TypeScript is a welcome contribution.
