### ISSUE TITLE
PATCH handler failing with no response

### ISSUE THREAD

**Issue by chriscapaci** [gajus/express-tus#3]
I have things set up where I can make a POST to create a new upload, I can use the ID returned from the POST in a HEAD call and get a successful response, so I know it was created successfully (btw, this is using the MemoryStorage for now as I try to set things up). However, when I then attempt to make a PATCH request, it gets to the part of the code where you set up the "pipeline" on the stream and fails. It never gets in to the generator function to yield the chunk, It just quietly exits your handler somehow and then proceeds to my error handler later on in the express sequence and returns a 404 as if the route didn't exist, which happens because nothing handled it and sent a response. 

So, do you have any idea why this would happen? I have no other details as I don't see anything logged in my application stdout/stderr. If there's a way to turn on logging in your code, please let me know and I'll try to gather more info. But maybe you can tell what's going on anyway? Or have some suggestions on things to try?

UPDATE: I have a little more info. I was playing around with editing the PATCH handler, specifically I removed the generator function in the pipeline call, and things worked after that. Obviously that looks necessary for when it's nota 5 byte test upload, but it proves that the generator function is causing the problem for me. Any idea why? I'm using TypeScript, so I've defined the type definitions for your module for use in my application, but things are being used in a very similar manner to your example documentation. Instead of applying the return from "createTusMiddleware" to the "app" directly, I have a Router that I'm applying it to, which should be doing the exact same thing. And, like I mention above, the other methods work, and this one is even being called, so the setup of the routing isn't a problem. But maybe there's something else I need to do to support the use of generators within my Express routing setup? I've not seen anything to suggest that I would, but maybe. Also, maybe it has to do with Node version? I'm currently using 12.18.3, and haven't tried any others, but that's my next try.

UPDATE 2: Tried 10.15.3 with no luck, but updating to 14.15.4 works! So, is Node v14 a requirement for this lib and I just didn't see that anywhere? Or should it work with 12? I believe generator functions are supported in 10 and 12 as well, but maybe something about your usage isn't? 

Anyway, I'm going to try to get my application to use v14, but if not, is there any way you can figure out how to get it to run with v12?

**Comment by gajus** [comment]
https://github.com/gajus/express-tus/blob/master/package.json#L53-L55

No plans to change this.

**Comment by chriscapaci** [comment]
Got it, thanks! I didn't look there, but thanks for pointing it out. Luckily I was able to update my project to use 14. Sorry for bothering you.
